### ISSUE TITLE
Enable Travis integration to get automatic spell checking of new pull requests

### ISSUE THREAD

**Issue by practicalswift** [lnbook/lnbook#49]
The PR #29 added automatic spell checking of new pull requests using `codespell`. For that to work the Travis-GitHub integration must be enabled.

**Comment by renepickhardt** [comment]
Yeah I already merged it but currently only @aantonop can activate this

**Comment by nopara73** [comment]
Just a tip: there's also GitHub actions now if you want to keep the tech stack lean: https://github.com/features/actions

**Comment by practicalswift** [comment]
@nopara73 GitHub Actions seems promising but I suggest we stick with Travis until GitHub Actions is generally available/out of beta. Travis is open for everybody and thus available for all clones of this repo :)

**Comment by aantonop** [comment]
> Just a tip: there's also GitHub actions now if you want to keep the tech stack lean: https://github.com/features/actions

I've been signed up for the beta of Github actions for many months. Still not available. We should proceed with Travis or some other CI solution. I'll look into it.

**Comment by practicalswift** [comment]
Now enabled! Closing! :)
